# Generated by Django 5.1.7 on 2025-03-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='assignment_marks',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='subject',
            name='final_exam_marks',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='subject',
            name='midterm_marks',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='subject',
            name='quiz_marks',
            field=models.FloatField(default=0.0),
        ),
    ]
