# Generated by Django 5.1.6 on 2025-03-25 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent_dashboard', '0003_subject_total_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='assignment_marks',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='final_exam_marks',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='midterm_marks',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='quiz_marks',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='total_marks',
        ),
        migrations.AlterField(
            model_name='subject',
            name='grade',
            field=models.CharField(default='N/A', max_length=2),
        ),
        migrations.CreateModel(
            name='SubjectPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_marks', models.FloatField(default=0.0)),
                ('quiz_marks', models.FloatField(default=0.0)),
                ('midterm_marks', models.FloatField(default=0.0)),
                ('final_exam_marks', models.FloatField(default=0.0)),
                ('total_marks', models.FloatField(default=0.0)),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='parent_dashboard.subject')),
            ],
        ),
    ]
