# Generated by Django 5.1.6 on 2025-03-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent_dashboard', '0004_remove_subject_assignment_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectperformance',
            name='grade',
            field=models.CharField(default='F', max_length=2),
        ),
    ]
