# Generated by Django 5.1.7 on 2025-03-27 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent_dashboard', '0005_subjectperformance_grade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='improvement_needed',
        ),
        migrations.AddField(
            model_name='subject',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectperformance',
            name='improvement_needed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='semester',
            name='gpa',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='subjectperformance',
            name='assignment_marks',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subjectperformance',
            name='final_exam_marks',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subjectperformance',
            name='grade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='subjectperformance',
            name='midterm_marks',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subjectperformance',
            name='quiz_marks',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subjectperformance',
            name='total_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
