# Generated by Django 5.1.7 on 2025-03-27 10:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent_dashboard', '0006_remove_subject_grade_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='semester',
            old_name='semester_number',
            new_name='year',
        ),
        migrations.AddField(
            model_name='semester',
            name='semester_name',
            field=models.CharField(choices=[('Spring', 'Spring'), ('Fall', 'Fall'), ('Summer', 'Summer')], default='Spring 2025', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('student', 'semester_name', 'year')},
        ),
    ]
