# Generated by Django 5.1.7 on 2025-03-21 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_semester_student_alter_subject_semester_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='student',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='semester',
        ),
        migrations.DeleteModel(
            name='ParentProfile',
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
